#!/usr/bin/env sh

# bar settings
yabai -m config status_bar                   off
yabai -m config status_bar_text_font         "SF UI:Regular:12.0"
yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
yabai -m config status_bar_background_color  0xff202020
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip   2 3 4 5 6 7
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_shadow                on
yabai -m config window_border                off
yabai -m config window_border_width          4
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   5

yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="Preferences$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^mpv$" manage=off
yabai -m rule --add app="^IINA$" manage=off
yabai -m rule --add app="^Slack$" manage=off
yabai -m rule --add app="^WhatsApp$" manage=off
yabai -m rule --add app="^Telegram$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="Activity Monitor" manage=off
yabai -m rule --add app="KeePassXC" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="Airmail" manage=off
yabai -m rule --add app="^Mail$" manage=off
yabai -m rule --add app="12C" manage=off
yabai -m rule --add app="Katalon Studio" manage=off

yabai -m rule --add title="^Open$" manage=off

# Picture in picture rules
# yabai -m rule --add app="Firefox Developer Edition" title="^$" sticky=on
yabai -m rule --add title="Picture-in-Picture" manage=off
yabai -m rule --add title="Picture-in-Picture" sticky=on
yabai -m rule --add title="Picture in Picture" manage=off

echo "yabai configuration loaded.."
