# vim: ft=zsh:syntax=zsh


export TERM=xterm-256color
export DISABLE_AUTO_TITLE="true"
export EDITOR="nvim"
export GIT_EDITOR=$EDITOR
export PAGER='less'

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export is_dev=1
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin:/opt/local/bin:/usr/local/git/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/share/npm/bin:/Library/Frameworks/Mono.framework/Commands:/Users/weslly/.local/bin:$HOME/.cargo/bin

export PATH="/usr/local/opt/qt5/bin:$PATH"
export PATH="/usr/local/opt/qt/bin:$PATH"


fpath=(
  '/usr/local/share/zsh/site-functions'
  $fpath
  )

export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
(( $+commands[nvim] )) && export MANPAGER="nvim -c 'set ft=man' -"

path=(
  /usr/local/{bin,sbin}
  /usr/local/opt/coreutils/libexec/gnubin
  /usr/local/opt/python/libexec/bin
  /usr/local/opt/curl/bin
  /usr/local/Cellar/git
  ${HOME}/.dotfiles/bin
  $path
)

if (( $+commands[yarn] )); then
  path+=($(yarn global bin))
fi


export LESS='-F -g -i -M -R -S -w -X -z-4'
